# Generated by Django 4.2.13 on 2024-11-01 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dbms", "0007_alter_bookissued_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookissued",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="dbms.libraryinventory"
            ),
        ),
        migrations.AlterField(
            model_name="bookissued",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
