# Generated by Django 4.2.13 on 2024-11-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dbms", "0008_alter_bookissued_book_alter_bookissued_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificatedistribution",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="certificatefeecollection",
            name="certificate",
        ),
        migrations.DeleteModel(
            name="ContactUs",
        ),
        migrations.RemoveField(
            model_name="libraryfinecollection",
            name="student",
        ),
        migrations.AddField(
            model_name="libraryfinecollection",
            name="member",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="dbms.librarymember",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CertificateDistribution",
        ),
        migrations.DeleteModel(
            name="CertificateFeeCollection",
        ),
    ]
