# Generated by Django 4.2.13 on 2024-11-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbms", "0009_remove_certificatedistribution_certificate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libraryfinecollection",
            old_name="member",
            new_name="member_id",
        ),
        migrations.RenameField(
            model_name="librarymember",
            old_name="student",
            new_name="member",
        ),
    ]
