# Generated by Django 4.2.13 on 2024-11-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbms", "0010_rename_member_libraryfinecollection_member_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libraryfinecollection",
            old_name="member_id",
            new_name="member",
        ),
    ]
