# Generated by Django 5.1.2 on 2024-11-04 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0011_rename_member_id_libraryfinecollection_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="librarymember",
            old_name="member",
            new_name="student",
        ),
    ]
