# Generated by Django 5.1.2 on 2024-11-04 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0012_rename_member_librarymember_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="librarymember",
            old_name="student",
            new_name="member",
        ),
    ]
