# Generated by Django 5.1.2 on 2024-11-06 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0012_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMarks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbms.streamcourse",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbms.faculty"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbms.registeredstudent",
                    ),
                ),
            ],
        ),
    ]
