# Generated by Django 5.1.2 on 2024-11-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0014_remove_coursemarks_course_remove_coursemarks_faculty_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="facultycourseassignment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="coursemarks",
            name="faculty_assignment",
        ),
        migrations.AddField(
            model_name="coursemarks",
            name="course",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="dbms.streamcourse",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursemarks",
            name="faculty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dbms.faculty",
            ),
            preserve_default=False,
        ),
    ]
