# Generated by Django 4.2.13 on 2024-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbms", "0016_feedback_faculty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registeredstudent",
            name="course",
        ),
        migrations.AddField(
            model_name="registeredstudent",
            name="course",
            field=models.ManyToManyField(to="dbms.streamcourse"),
        ),
    ]
