# Generated by Django 4.2.13 on 2024-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbms", "0005_alter_bookissued_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookissued",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
