from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from dbms.views import CustomLoginView
from dbms.views import (
    home,
    student_view,
    certificate_view,
    feedback_view,
    library_management_view,
    website_management_view,
    department_list, department_create,
    news_notice_list, news_notice_create,
    faculty_list, faculty_create,
    image_gallery_list, image_gallery_create,
    video_gallery_list, video_gallery_create,
    library_inventory_list, library_member_list,
    grievance_list,
    feedback_list,
    show_students,
    show_admissions,
    show_courses,
    show_fees,
    show_grievances,
    show_feedback,
    show_enquiries,
    show_inventory,
    show_members,
    show_fines,
    show_issued_books,
    show_certificates,
    show_applications,
    show_news_notices,
    show_departments,
    show_sliders,
    show_tickers,
    show_gallery,
    show_videos,
    show_faculty,
    about, contact,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', CustomLoginView.as_view(), name='login'),  # Root page is now the login page
    path('home/', home, name='home'),  # Ensure there's a route for the home page
    path('certificate/', certificate_view, name='certificate'),
    path('feedback/', feedback_view, name='feedback'),
    path('student/', student_view, name='student'),
    path('library/', library_management_view, name='library'),
    path('management/', website_management_view, name='management'),
    path('departments/', department_list, name='department_list'),
    path('departments/create/', department_create, name='department_create'),
    path('news-notices/', news_notice_list, name='news_notice_list'),
    path('news-notices/create/', news_notice_create, name='news_notice_create'),
    path('faculty/', faculty_list, name='faculty_list'),
    path('faculty/create/', faculty_create, name='faculty_create'),
    path('image-gallery/', image_gallery_list, name='image_gallery_list'),
    path('image-gallery/create/', image_gallery_create, name='image_gallery_create'),
    path('video-gallery/', video_gallery_list, name='video_gallery_list'),
    path('video-gallery/create/', video_gallery_create, name='video_gallery_create'),
    path('library/inventory/', library_inventory_list, name='library_inventory_list'),
    path('library/members/', library_member_list, name='library_member_list'),
    path('grievances/', grievance_list, name='grievance_list'),
    path('feedback/', feedback_list, name='feedback_list'),
    path('show-students/', show_students, name='show_students'),
    path('show-admissions/', show_admissions, name='show_admissions'),
    path('show-courses/', show_courses, name='show_courses'),
    path('show-fees/', show_fees, name='show_fees'),
    path('show-grievances/', show_grievances, name='show_grievances'),
    path('show-feedback/', show_feedback, name='show_feedback'),
    path('show-enquiries/', show_enquiries, name='show_enquiries'),
    path('show-inventory/', show_inventory, name='show_inventory'),
    path('show-members/', show_members, name='show_members'),
    path('show-fines/', show_fines, name='show_fines'),
    path('show-issued-books/', show_issued_books, name='show_issued_books'),
    path('show-certificates/', show_certificates, name='show_certificates'),
    path('show-applications/', show_applications, name='show_applications'),
    path('show-news-notices/', show_news_notices, name='show_news_notices'),
    path('show-departments/', show_departments, name='show_departments'),
    path('show-sliders/', show_sliders, name='show_sliders'),
    path('show-tickers/', show_tickers, name='show_tickers'),
    path('show-gallery/', show_gallery, name='show_gallery'),
    path('show_videos/', show_videos, name='show_videos'),
    path('show-faculty/', show_faculty, name='show_faculty'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]